/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWhoToCallRouteImport } from './routes/_authenticated/who-to-call'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedToastRouteImport } from './routes/_authenticated/toast'
import { Route as AuthenticatedTargetsRouteImport } from './routes/_authenticated/targets'
import { Route as AuthenticatedSquareRouteImport } from './routes/_authenticated/square'
import { Route as AuthenticatedPnlQtrRouteImport } from './routes/_authenticated/pnl-qtr'
import { Route as AuthenticatedPnlBonusRouteImport } from './routes/_authenticated/pnl-bonus'
import { Route as AuthenticatedPnlRouteImport } from './routes/_authenticated/pnl'
import { Route as AuthenticatedPermissionsRouteImport } from './routes/_authenticated/permissions'
import { Route as AuthenticatedLocationsRouteImport } from './routes/_authenticated/locations'
import { Route as AuthenticatedDessertsRouteImport } from './routes/_authenticated/desserts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWhoToCallRoute = AuthenticatedWhoToCallRouteImport.update({
  id: '/who-to-call',
  path: '/who-to-call',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToastRoute = AuthenticatedToastRouteImport.update({
  id: '/toast',
  path: '/toast',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTargetsRoute = AuthenticatedTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSquareRoute = AuthenticatedSquareRouteImport.update({
  id: '/square',
  path: '/square',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPnlQtrRoute = AuthenticatedPnlQtrRouteImport.update({
  id: '/pnl-qtr',
  path: '/pnl-qtr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPnlBonusRoute = AuthenticatedPnlBonusRouteImport.update({
  id: '/pnl-bonus',
  path: '/pnl-bonus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPnlRoute = AuthenticatedPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissionsRoute =
  AuthenticatedPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLocationsRoute = AuthenticatedLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDessertsRoute = AuthenticatedDessertsRouteImport.update({
  id: '/desserts',
  path: '/desserts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desserts': typeof AuthenticatedDessertsRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/square': typeof AuthenticatedSquareRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/toast': typeof AuthenticatedToastRoute
  '/users': typeof AuthenticatedUsersRoute
  '/who-to-call': typeof AuthenticatedWhoToCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desserts': typeof AuthenticatedDessertsRoute
  '/locations': typeof AuthenticatedLocationsRoute
  '/permissions': typeof AuthenticatedPermissionsRoute
  '/pnl': typeof AuthenticatedPnlRoute
  '/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/square': typeof AuthenticatedSquareRoute
  '/targets': typeof AuthenticatedTargetsRoute
  '/toast': typeof AuthenticatedToastRoute
  '/users': typeof AuthenticatedUsersRoute
  '/who-to-call': typeof AuthenticatedWhoToCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desserts': typeof AuthenticatedDessertsRoute
  '/_authenticated/locations': typeof AuthenticatedLocationsRoute
  '/_authenticated/permissions': typeof AuthenticatedPermissionsRoute
  '/_authenticated/pnl': typeof AuthenticatedPnlRoute
  '/_authenticated/pnl-bonus': typeof AuthenticatedPnlBonusRoute
  '/_authenticated/pnl-qtr': typeof AuthenticatedPnlQtrRoute
  '/_authenticated/square': typeof AuthenticatedSquareRoute
  '/_authenticated/targets': typeof AuthenticatedTargetsRoute
  '/_authenticated/toast': typeof AuthenticatedToastRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/who-to-call': typeof AuthenticatedWhoToCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/desserts'
    | '/locations'
    | '/permissions'
    | '/pnl'
    | '/pnl-bonus'
    | '/pnl-qtr'
    | '/square'
    | '/targets'
    | '/toast'
    | '/users'
    | '/who-to-call'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/desserts'
    | '/locations'
    | '/permissions'
    | '/pnl'
    | '/pnl-bonus'
    | '/pnl-qtr'
    | '/square'
    | '/targets'
    | '/toast'
    | '/users'
    | '/who-to-call'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/desserts'
    | '/_authenticated/locations'
    | '/_authenticated/permissions'
    | '/_authenticated/pnl'
    | '/_authenticated/pnl-bonus'
    | '/_authenticated/pnl-qtr'
    | '/_authenticated/square'
    | '/_authenticated/targets'
    | '/_authenticated/toast'
    | '/_authenticated/users'
    | '/_authenticated/who-to-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/who-to-call': {
      id: '/_authenticated/who-to-call'
      path: '/who-to-call'
      fullPath: '/who-to-call'
      preLoaderRoute: typeof AuthenticatedWhoToCallRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/toast': {
      id: '/_authenticated/toast'
      path: '/toast'
      fullPath: '/toast'
      preLoaderRoute: typeof AuthenticatedToastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/targets': {
      id: '/_authenticated/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AuthenticatedTargetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/square': {
      id: '/_authenticated/square'
      path: '/square'
      fullPath: '/square'
      preLoaderRoute: typeof AuthenticatedSquareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pnl-qtr': {
      id: '/_authenticated/pnl-qtr'
      path: '/pnl-qtr'
      fullPath: '/pnl-qtr'
      preLoaderRoute: typeof AuthenticatedPnlQtrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pnl-bonus': {
      id: '/_authenticated/pnl-bonus'
      path: '/pnl-bonus'
      fullPath: '/pnl-bonus'
      preLoaderRoute: typeof AuthenticatedPnlBonusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pnl': {
      id: '/_authenticated/pnl'
      path: '/pnl'
      fullPath: '/pnl'
      preLoaderRoute: typeof AuthenticatedPnlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissions': {
      id: '/_authenticated/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof AuthenticatedPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locations': {
      id: '/_authenticated/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AuthenticatedLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desserts': {
      id: '/_authenticated/desserts'
      path: '/desserts'
      fullPath: '/desserts'
      preLoaderRoute: typeof AuthenticatedDessertsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDessertsRoute: typeof AuthenticatedDessertsRoute
  AuthenticatedLocationsRoute: typeof AuthenticatedLocationsRoute
  AuthenticatedPermissionsRoute: typeof AuthenticatedPermissionsRoute
  AuthenticatedPnlRoute: typeof AuthenticatedPnlRoute
  AuthenticatedPnlBonusRoute: typeof AuthenticatedPnlBonusRoute
  AuthenticatedPnlQtrRoute: typeof AuthenticatedPnlQtrRoute
  AuthenticatedSquareRoute: typeof AuthenticatedSquareRoute
  AuthenticatedTargetsRoute: typeof AuthenticatedTargetsRoute
  AuthenticatedToastRoute: typeof AuthenticatedToastRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWhoToCallRoute: typeof AuthenticatedWhoToCallRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDessertsRoute: AuthenticatedDessertsRoute,
  AuthenticatedLocationsRoute: AuthenticatedLocationsRoute,
  AuthenticatedPermissionsRoute: AuthenticatedPermissionsRoute,
  AuthenticatedPnlRoute: AuthenticatedPnlRoute,
  AuthenticatedPnlBonusRoute: AuthenticatedPnlBonusRoute,
  AuthenticatedPnlQtrRoute: AuthenticatedPnlQtrRoute,
  AuthenticatedSquareRoute: AuthenticatedSquareRoute,
  AuthenticatedTargetsRoute: AuthenticatedTargetsRoute,
  AuthenticatedToastRoute: AuthenticatedToastRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWhoToCallRoute: AuthenticatedWhoToCallRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
